# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'New'), ('O', 'Ongoing'), ('R', 'Resolved'), ('C', 'Closed'), ('I', 'Invalid')], default='N', max_length=1, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name', blank=False, null=False)),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail', blank=False, null=False)),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='phone')),
                ('message', models.TextField(verbose_name='message', blank=False, null=False)),
                ('ip', models.GenericIPAddressField(verbose_name='contact ip')),
            ],
        ),
    ]
